# Generated by Django 4.1.2 on 2022-10-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="discord_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
